name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
  workflow_dispatch:
  repository_dispatch:
    types: [steamcmd-base-updated]

jobs:
  echo-base-update:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Echo base image update
        run: echo "Base image steamcmd-base has been updated, triggering rebuild of steamcmd-wine. ImageID ${{ github.event.client_payload.imageid }}Digest ${{ github.event.client_payload.digest }}"

  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      imageid: ${{ steps.bap.outputs.imageid }}
      digest: ${{ steps.bap.outputs.digest }}
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Build and push
        id: bap
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            teejo75/steamcmd-wine:latest
            ghcr.io/teejo75/steamcmd-wine:latest
  external-dispatch:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch steamcmd-wine-updated event
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.PAT_PUBLIC_REPO }}
          repository: rhavinx/starrupture
          event-type: steamcmd-wine-updated
          client-payload: |
            {
              "imageid": "${{ needs.build-and-push.outputs.imageid }}",
              "digest": "${{ needs.build-and-push.outputs.digest }}"
            }